const { CourseLevel, LanguageCode, LayoutCode } = require('@prisma/client');

const LOWERCASE = 'abcdefghijklmnñopqrstuvwxyz';
const UPPERCASE = 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';
const ACCENTED = 'áéíóúüÁÉÍÓÚÜ';
const SPACE = ' ';

function characters(value) {
  return [...new Set(Array.from(value))];
}

function practice({
  slug,
  title,
  description,
  objective,
  content,
  focusKeys,
  reviewKeys = [],
  allowed,
  order,
  difficulty = 1,
  estimatedSeconds = 60,
  minAccuracy = 95,
  maxTargetKeyErrors = 2,
  hideLiveWpm = true,
  audioUrl = null,
  instructions = 'Escribe con calma y vuelve a la posición base después de cada movimiento.',
}) {
  return {
    slug,
    title,
    description,
    objective,
    instructions,
    content,
    type: 'practice',
    focusKeys,
    reviewKeys,
    allowedCharacters: characters(allowed),
    targetKeys: focusKeys,
    difficulty,
    estimatedSeconds,
    minAccuracy,
    maxTargetKeyErrors,
    hideLiveWpm,
    mediaUrl: null,
    audioUrl,
    required: true,
    order,
  };
}

function introduction({
  slug,
  title,
  description,
  objective,
  content,
  targetKeys,
  focusKeys = targetKeys,
  reviewKeys = [],
  order,
  difficulty = 1,
  estimatedSeconds = 40,
  audioUrl = null,
}) {
  return {
    slug,
    title,
    description,
    objective,
    instructions: 'Pulsa las teclas resaltadas para confirmar su posición.',
    content,
    type: 'explanatory',
    focusKeys,
    reviewKeys,
    allowedCharacters: [],
    targetKeys,
    difficulty,
    estimatedSeconds,
    minAccuracy: 100,
    maxTargetKeyErrors: 0,
    hideLiveWpm: true,
    mediaUrl: null,
    audioUrl,
    required: true,
    order,
  };
}

const home = 'asdfghjklñ';
const homeEi = `${home}ei`;
const homeEiRtYu = `${homeEi}rtyu`;
const topComplete = `${homeEiRtYu}qwop`;
const indexBottom = `${topComplete}vbnm`;
const allLower = `${LOWERCASE}`;
const allAlphabetic = `${LOWERCASE}${UPPERCASE}${ACCENTED}${SPACE}`;
const allDailyCharacters = `${allAlphabetic}1234567890.,;¿?¡!`;

module.exports = {
  slug: 'caracteres-alfabeticos-es',
  name: 'Mecanografía',
  description:
    'Desarrolla velocidad y precisión al escribir con caracteres alfanuméricos y acentuación mediante ejercicios progresivos.',
  languageCode: LanguageCode.es,
  localeCode: 'es-latam',
  level: CourseLevel.BEGINNER,
  supportedLayouts: [LayoutCode.QWERTY_ES, LayoutCode.QWERTY_LATAM],
  curriculumVersion: 1,
  estimatedMinutes: 420,
  modules: [
    {
      slug: 'anclas',
      title: 'Anclas y posición base',
      description: 'Aprende a encontrar F y J sin mirar.',
      order: 1,
      lessons: [
        introduction({
          slug: 'preparacion-y-guia',
          title: 'Antes de empezar',
          description: 'Mira el teclado guía y coloca tus manos como muestran las imágenes.',
          objective: 'Prepararse y encontrar la posición base en F y J.',
          content: 'Mira el teclado guía, coloca tus manos como muestran las imágenes y presiona F y J para confirmar.',
          targetKeys: ['F', 'J'],
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-1-es.mp3',
          order: 1,
        }),
        practice({
          slug: 'anclas-f-j-practica',
          title: 'Práctica con F y J',
          description: 'Pulsa las dos teclas guía con calma.',
          objective: 'Sentir la posición de F y J sin mirar el teclado.',
          content: 'fj jf fj jf',
          focusKeys: ['f', 'j'],
          allowed: `fj${SPACE}`,
          order: 2,
        }),
        introduction({
          slug: 'd-k-guia',
          title: 'Teclas D y K',
          description: 'Usa los dedos medios para presionar D y K.',
          objective: 'Presionar D y K con los dedos medios.',
          content:
            'Manteniendo tus dedos índice sobre las teclas F y J, sin presionarlas, usa tus dedos medios para presionar las teclas D y K.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-5-es.mp3',
          targetKeys: ['D', 'K'],
          order: 5,
        }),
        practice({
          slug: 'd-k-practica',
          title: 'Práctica con D y K',
          description: 'Mueve solo los dedos medios.',
          objective: 'Practicar D y K con precisión.',
          content: 'dk kd dk kd',
          focusKeys: ['d', 'k'],
          reviewKeys: ['f', 'j'],
          allowed: `dfjk${SPACE}`,
          order: 6,
        }),
        introduction({
          slug: 's-l-guia',
          title: 'Teclas S y L',
          description: 'Usa los dedos anulares para presionar S y L.',
          objective: 'Presionar S y L con los dedos anulares.',
          content: 'Usa tus dedos anulares para presionar las teclas S y L.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-7-es.mp3',
          targetKeys: ['S', 'L'],
          order: 7,
        }),
        practice({
          slug: 's-l-practica',
          title: 'Práctica con S y L',
          description: 'Mueve solo los dedos anulares.',
          objective: 'Practicar S y L con precisión.',
          content: 'sl ls sl ls',
          focusKeys: ['s', 'l'],
          reviewKeys: ['f', 'j'],
          allowed: `sfjl${SPACE}`,
          order: 8,
        }),
        introduction({
          slug: 'a-enie-guia',
          title: 'Teclas A y Ñ',
          description: 'Usa los dedos meñiques para presionar A y Ñ.',
          objective: 'Presionar A y Ñ con los dedos meñiques.',
          content: 'Usa tus dedos meñiques para presionar las teclas A y Ñ.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-9-es.mp3',
          targetKeys: ['A', 'Ñ'],
          order: 9,
        }),
        practice({
          slug: 'a-enie-practica',
          title: 'Práctica con A y Ñ',
          description: 'Mueve solo los meñiques.',
          objective: 'Practicar A y Ñ con precisión.',
          content: 'añ ña añ ña',
          focusKeys: ['a', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `afjñ${SPACE}`,
          order: 10,
        }),
        introduction({
          slug: 'posicion-descanso',
          title: 'Posición de descanso',
          description: 'Mantén los dedos en su posición base y usa el pulgar para el espacio.',
          objective: 'Mantener la posición de descanso y usar la barra espaciadora.',
          content:
            'Esta posición se llama posición de descanso, como su nombre lo indica es como deben reposar los dedos cuando no estás tecleando, con el pulgar de tu mano dominante presiona la barra espaciadora.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-5-es.mp3',
          targetKeys: ['A', 'S', 'D', 'F', 'J', 'K', 'L', 'Ñ', ' '],
          order: 5,
        }),
        introduction({
          slug: 'g-h-guia',
          title: 'Teclas G y H',
          description: 'Mueve tus dedos índices hacia el centro para llegar a G y H.',
          objective: 'Presionar G y H sin perder la referencia en F y J.',
          content:
            'Mueve tus dedos índice hacia el centro para presionar las teclas G y H, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-6-es.mp3',
          targetKeys: ['G', 'H'],
          order: 6,
        }),
        practice({
          slug: 'fila-guia-practica-1',
          title: 'Fila guía - Introducción',
          description: 'Practica en pares.',
          objective: 'Familiarizarse con fila guia.',
          content: 'fj jf fj jf dk kd dk kd sl ls sl ls añ ña añ ña gh hg gh hg',
          focusKeys: ['f', 'j'],
          reviewKeys: [],
          allowed: `asdfghjklñ${SPACE}`,
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-7-es.mp3',
          order: 7,
        }),
        practice({
          slug: 'fila-guia-practica-2',
          title: 'Fila guía - Pares básicos',
          description: 'Practica en pares.',
          objective: 'Familiarizarse con fila guia.',
          content: 'as sa df fd gh hg jk kj lñ ñl sd ds fg gf hj jh kl lk',
          focusKeys: ['f', 'j'],
          reviewKeys: [],
          allowed: `asdfghjklñ${SPACE}`,
          order: 8,
        }),
        practice({
          slug: 'fila-guia-practica-3',
          title: 'Dedos independientes',
          description: 'Practica cada dedo de las dos manos.',
          objective: 'Mover cada dedo de forma independiente.',
          content: 'asdfg gfdsa asdfg gfdsa ñlkjh hjklñ ñlkjh hjklñ',
          focusKeys: ['a', 's', 'd'],
          reviewKeys: ['f'],
          allowed: `asdfghjklñ${SPACE}`,
          order: 9,
        }),
        practice({
          slug: 'fila-guia-practica-4',
          title: 'Alternancia básica',
          description: 'Integra ambas manos.',
          objective: 'Alternar entre mano izquierda y derecha.',
          content: 'fj jf dk kd sl ls añ ña gh hg',
          focusKeys: ['d', 'k', 's', 'l'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfghjklñ${SPACE}`,
          order: 10,
        }),
        practice({
          slug: 'fila-guia-practica-5',
          title: 'Alternancia básica 2',
          description: 'Integra ambas manos.',
          objective: 'Alternar entre mano izquierda y derecha.',
          content: 'ad sf jl kñ ñk lj fs da sl dk ña gh',
          focusKeys: ['d', 'k', 's', 'l'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfghjklñ${SPACE}`,
          order: 11,
        }),
        practice({
          slug: 'fila-guia-practica-6',
          title: 'Patrones comunes',
          description: 'Coordina movimientos entre manos.',
          objective: 'Escribir combinaciones letra a letra.',
          content: 'fa ja sa la da ña la fa sa da ja ña',
          focusKeys: ['a', 's', 'd', 'l', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfjklñ${SPACE}`,
          order: 12,
        }),
        practice({
          slug: 'fila-guia-practica-7',
          title: 'Patrones comunes 2',
          description: 'Practica patrones comunes de la fila guía.',
          objective: 'Mejorar la fluidez entre manos.',
          content: 'ala sal sala dada hada gala gafas falla halla',
          focusKeys: ['a', 's', 'd', 'g', 'h', 'l', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfghjklñ${SPACE}`,
          order: 13,
        }),
        practice({
          slug: 'fila-guia-practica-8',
          title: 'Secuencias de dedos',
          description: 'Practica dedos adyacentes.',
          objective: 'Mover dedos adyacentes coordinadamente.',
          content: 'as sa sd ds df fd f j jk kj kl lk lñ ñl',
          focusKeys: ['a', 's', 'd', 'k', 'l', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfjklñ${SPACE}`,
          order: 14,
        }),
        practice({
          slug: 'fila-guia-practica-9',
          title: 'Palabras cortas con espacio',
          description: 'Introduce la barra espaciadora.',
          objective: 'Escribir palabras de 2-3 letras.',
          content: 'ala sal dada hada gala falla halla daga gafas añada',
          focusKeys: ['g', 'h', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfghjklñ${SPACE}`,
          order: 15,
        }),
        practice({
          slug: 'fila-guia-practica-11',
          title: 'Palabras con todas las letras',
          description: 'Incluye todas las letras de la fila guía.',
          objective: 'Escribir palabras que usan toda la fila guía.',
          content: 'sal ala sala dada hada gala gafas falla halla',
          focusKeys: ['a', 's', 'd', 'k', 'l', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfghjklñ${SPACE}`,
          order: 16,
        }),
        practice({
          slug: 'fila-guia-practica-12',
          title: 'Repaso de la fila guía',
          description: 'Repite secuencias con calma y precisión.',
          objective: 'Mantener la posición de descanso al escribir.',
          content: 'asdf jklñ fdsa ñlkj as jk dl fñ sa kñ dlf',
          focusKeys: ['a', 's', 'd', 'k', 'l', 'ñ'],
          reviewKeys: ['f', 'j'],
          allowed: `asdfjklñ${SPACE}`,
          order: 17,
        }),
        introduction({
          slug: 'fila-superior-q-p',
          title: 'Teclas Q y P',
          description: 'Usa los dedos meñiques para presionar Q y P.',
          objective: 'Presionar Q y P con los dedos meñiques.',
          content:
            'Usa tus dedos meñiques para presionar las teclas Q y P, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-18-es.mp3',
          targetKeys: ['Q', 'P'],
          order: 18,
        }),
        introduction({
          slug: 'fila-superior-w-o',
          title: 'Teclas W y O',
          description: 'Usa los dedos anulares para presionar W y O.',
          objective: 'Presionar W y O con los dedos anulares.',
          content:
            'Usa tus dedos anulares para presionar las teclas W y O, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-19-es.mp3',
          targetKeys: ['W', 'O'],
          order: 19,
        }),
        introduction({
          slug: 'fila-superior-e-i',
          title: 'Teclas E e I',
          description: 'Usa los dedos medios para presionar E e I.',
          objective: 'Presionar E e I con los dedos medios.',
          content:
            'Usa tus dedos medios para presionar las teclas E e I, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-20-es.mp3',
          targetKeys: ['E', 'I'],
          order: 20,
        }),
        introduction({
          slug: 'fila-superior-r-u',
          title: 'Teclas R y U',
          description: 'Usa los dedos índices para presionar R y U.',
          objective: 'Presionar R y U con los dedos índices.',
          content:
            'Usa tus dedos índices para presionar las teclas R y U, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-21-es.mp3',
          targetKeys: ['R', 'U'],
          order: 21,
        }),
        introduction({
          slug: 'fila-superior-t-y',
          title: 'Teclas T e Y',
          description: 'Extiende tus dedos índices para llegar a T e Y.',
          objective: 'Presionar T e Y sin perder la referencia en F y J.',
          content:
            'Usa tus dedos índices para presionar las teclas T e Y, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-22-es.mp3',
          targetKeys: ['T', 'Y'],
          order: 22,
        }),
        practice({
          slug: 'fila-superior-practica-1',
          title: 'Fila superior - Introducción',
          description: 'Practica las teclas de la fila superior.',
          objective: 'Familiarizarse con la posición de las teclas QWERTYUIOP.',
          content: 'qw qp op po we ew oi io rt tr yu uy ty yt ui iu',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: [],
          allowed: `qwertyuiop${SPACE}`,
          order: 23,
        }),
        practice({
          slug: 'fila-superior-practica-2',
          title: 'Fila superior - Pares básicos',
          description: 'Practica pares de teclas adyacentes.',
          objective: 'Coordinar movimientos entre dedos de la fila superior.',
          content: 'qw we er rt ty yu ui io op po oi iu uy yt tr re ew wq',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: [],
          allowed: `qwertyuiop${SPACE}`,
          order: 24,
        }),
        practice({
          slug: 'fila-superior-practica-3',
          title: 'Mano izquierda - Fila superior',
          description: 'Practica las teclas de la mano izquierda.',
          objective: 'Mover los dedos izquierdos en la fila superior.',
          content: 'q w e r t t r e w q qw we er rt tr re ew wq t r e w q',
          focusKeys: ['q', 'w', 'e', 'r', 't'],
          reviewKeys: [],
          allowed: `qwert${SPACE}`,
          order: 25,
        }),
        practice({
          slug: 'fila-superior-practica-4',
          title: 'Mano derecha - Fila superior',
          description: 'Practica las teclas de la mano derecha.',
          objective: 'Mover los dedos derechos en la fila superior.',
          content: 'y u i o p p o i u y yu ui io op po oi iu uy p o i u y',
          focusKeys: ['y', 'u', 'i', 'o', 'p'],
          reviewKeys: [],
          allowed: `yuiop${SPACE}`,
          order: 26,
        }),
        practice({
          slug: 'fila-superior-practica-5',
          title: 'Alternancia fila superior',
          description: 'Alterna entre mano izquierda y derecha en fila superior.',
          objective: 'Mejorar la coordinación entre ambas manos.',
          content: 'q y w u e i r o t p p t o r i e u w y q y u i o p q w e r',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: [],
          allowed: `qwertyuiop${SPACE}`,
          order: 27,
        }),
        practice({
          slug: 'fila-superior-practica-6',
          title: 'Patrones comunes',
          description: 'Coordina movimientos entre ambas manos.',
          objective: 'Escribir combinaciones letra a letra.',
          content: 'q w q e w r e t r y t u y i u o i p o q w e r t y u i o p',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `qwertyuiopasdfjklñ${SPACE}`,
          order: 28,
        }),
        practice({
          slug: 'fila-superior-practica-7',
          title: 'Patrones comunes 2',
          description: 'Patrones alternados de fila superior.',
          objective: 'Mejorar la fluidez entre manos.',
          content: 'qw er ty ui op po ui ty er qw we rt yu io op po io yu rt',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `qwertyuiopasdfjklñ${SPACE}`,
          order: 29,
        }),
        practice({
          slug: 'fila-superior-practica-8',
          title: 'Combinaciones con fila guía',
          description: 'Integra fila superior con fila guía.',
          objective: 'Transicionar entre fila superior y fila guía.',
          content: 'qa ws ed rf tg yh uj ik ol ñp pñ lo ki ju hy gt fr de sw',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `qwertyuiopasdfghjklñ${SPACE}`,
          order: 30,
        }),
        practice({
          slug: 'fila-superior-practica-9',
          title: 'Palabras con fila superior',
          description: 'Practica palabras usando principalmente fila superior.',
          objective: 'Escribir palabras con teclas de fila superior.',
          content: 'tu yo pe pi te ti to po que qui pro por tri tupe tiro puro',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `qwertyuiopasdfjklñ${SPACE}`,
          order: 31,
        }),
        practice({
          slug: 'fila-superior-practica-10',
          title: 'Combinaciones avanzadas',
          description: 'Secuencias mixtas para mayor velocidad.',
          objective: 'Aumentar la velocidad en fila superior.',
          content: 'qwertyuiop poiuytrewq qwerty poiuyt rewq yuiop asdf',
          focusKeys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `qwertyuiopasdfjklñ${SPACE}`,
          order: 32,
        }),
        introduction({
          slug: 'fila-inferior-z-guion',
          title: 'Teclas Z y -',
          description: 'Usa los dedos meñiques para presionar Z y -.',
          objective: 'Presionar Z y - con los dedos meñiques.',
          content:
            'Usa tus dedos meñiques para presionar las teclas Z y -, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-33-es.mp3',
          targetKeys: ['Z', '-'],
          order: 33,
        }),
        introduction({
          slug: 'fila-inferior-x-punto',
          title: 'Teclas X y .',
          description: 'Usa los dedos anulares para presionar X y .',
          objective: 'Presionar X y . con los dedos anulares.',
          content:
            'Usa tus dedos anulares para presionar las teclas X y ., luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-34-es.mp3',
          targetKeys: ['X', '.'],
          order: 34,
        }),
        introduction({
          slug: 'fila-inferior-c-coma',
          title: 'Teclas C y ,',
          description: 'Usa los dedos medios para presionar C y ,',
          objective: 'Presionar C y , con los dedos medios.',
          content:
            'Usa tus dedos medios para presionar las teclas C y ,, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-35-es.mp3',
          targetKeys: ['C', ','],
          order: 35,
        }),
        introduction({
          slug: 'fila-inferior-v-m',
          title: 'Teclas V y M',
          description: 'Usa los dedos índices para presionar V y M.',
          objective: 'Presionar V y M con los dedos índices.',
          content:
            'Usa tus dedos índices para presionar las teclas V y M, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-36-es.mp3',
          targetKeys: ['V', 'M'],
          order: 36,
        }),
        introduction({
          slug: 'fila-inferior-b-n',
          title: 'Teclas B y N',
          description: 'Extiende tus dedos índices para llegar a B y N.',
          objective: 'Presionar B y N sin perder la referencia en F y J.',
          content:
            'Usa tus dedos índices para presionar las teclas B y N, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-37-es.mp3',
          targetKeys: ['B', 'N'],
          order: 37,
        }),
        practice({
          slug: 'fila-inferior-practica-1',
          title: 'Fila inferior - Introducción',
          description: 'Practica las teclas de la fila inferior.',
          objective: 'Familiarizarse con la posición de las teclas ZXCVBNM,.-',
          content: 'zx xz cv vc bn nb m, ,m .- -. zxcvb nm,.-',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: [],
          allowed: `zxcvbnm,.-ñ_${SPACE}`,
          order: 38,
        }),
        practice({
          slug: 'fila-inferior-practica-2',
          title: 'Fila inferior - Pares básicos',
          description: 'Practica pares de teclas adyacentes.',
          objective: 'Coordinar movimientos entre dedos de la fila inferior.',
          content: 'zx xc cv vb bn nm m, ,. .- -. ,. .- m, nm bn vb cv xc zx',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: [],
          allowed: `zxcvbnm,.-${SPACE}`,
          order: 39,
        }),
        practice({
          slug: 'fila-inferior-practica-3',
          title: 'Mano izquierda - Fila inferior',
          description: 'Practica las teclas de la mano izquierda.',
          objective: 'Mover los dedos izquierdos en la fila inferior.',
          content: 'z x c v b b v c x z zx xc cv vb bv vc cx xz b v c x z',
          focusKeys: ['z', 'x', 'c', 'v', 'b'],
          reviewKeys: [],
          allowed: `zxcvb${SPACE}`,
          order: 40,
        }),
        practice({
          slug: 'fila-inferior-practica-4',
          title: 'Mano derecha - Fila inferior',
          description: 'Practica las teclas de la mano derecha.',
          objective: 'Mover los dedos derechos en la fila inferior.',
          content: 'n m , . - - . , m n nm m, ,. .- -. ,. m, nm - . , m n',
          focusKeys: ['n', 'm', ',', '.', '-'],
          reviewKeys: [],
          allowed: `nm,.-${SPACE}`,
          order: 41,
        }),
        practice({
          slug: 'fila-inferior-practica-5',
          title: 'Patrones comunes',
          description: 'Coordina movimientos entre ambas manos.',
          objective: 'Escribir combinaciones letra a letra.',
          content: 'z n x m c , v . b - - b . v , c m x n z z x c v b n m , . -',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `zxcvbnm,.-asdfjklñ${SPACE}`,
          order: 42,
        }),
        practice({
          slug: 'fila-inferior-practica-6',
          title: 'Alternancia fila inferior',
          description: 'Alterna entre mano izquierda y derecha en fila inferior.',
          objective: 'Mejorar la coordinación entre ambas manos.',
          content: 'z n x m c , v . b - - b . v , c m x n z z x c v b n m , . -',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: [],
          allowed: `zxcvbnm,.-${SPACE}`,
          order: 43,
        }),
        practice({
          slug: 'fila-inferior-practica-7',
          title: 'Combinaciones con fila guía',
          description: 'Integra fila inferior con fila guía.',
          objective: 'Transicionar entre fila inferior y fila guía.',
          content: 'za xs cd vf bg hn jm k, l. ñ- ñl .k ,j mh ng bf dv cs xa',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `zxcvbnm,.-asdfghjklñ${SPACE}`,
          order: 44,
        }),
        practice({
          slug: 'fila-inferior-practica-8',
          title: 'Patrones comunes 2',
          description: 'Patrones alternados de fila inferior.',
          objective: 'Mejorar la fluidez entre manos.',
          content: 'zx cv bn m, .- ,. nm vb cx zx m, .- bn cv zx m, .- bn cv zx',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `zxcvbnm,.-asdfjklñ${SPACE}`,
          order: 45,
        }),
        practice({
          slug: 'fila-inferior-practica-9',
          title: 'Palabras con fila inferior',
          description: 'Practica palabras usando principalmente fila inferior.',
          objective: 'Escribir palabras con teclas de fila inferior.',
          content: 'mi ni vi si za ex no lo bo yo mo va ca da fe me el',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `zxcvbnm,.-asdfjklñeiouy${SPACE}`,
          order: 46,
        }),
        practice({
          slug: 'fila-inferior-practica-10',
          title: 'Combinaciones avanzadas',
          description: 'Secuencias mixtas para mayor velocidad.',
          objective: 'Aumentar la velocidad en fila inferior.',
          content: 'zxcvbnm,.- -.,mnbvcxz zxcvbnm ,.- m, n. bv cx zx cv bn m, .-',
          focusKeys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '-'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `zxcvbnm,.-asdfjklñ${SPACE}`,
          order: 47,
        }),
        introduction({
          slug: 'fila-numerica-1-0',
          title: 'Teclas 1 y 0',
          description: 'Usa los dedos meñiques para presionar 1 y 0.',
          objective: 'Presionar 1 y 0 con los dedos meñiques.',
          content:
            'Usa tus dedos meñiques para presionar las teclas 1 y 0, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-48-es.mp3',
          targetKeys: ['1', '0'],
          order: 48,
        }),
        introduction({
          slug: 'fila-numerica-2-9',
          title: 'Teclas 2 y 9',
          description: 'Usa los dedos anulares para presionar 2 y 9.',
          objective: 'Presionar 2 y 9 con los dedos anulares.',
          content:
            'Usa tus dedos anulares para presionar las teclas 2 y 9, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-49-es.mp3',
          targetKeys: ['2', '9'],
          order: 49,
        }),
        introduction({
          slug: 'fila-numerica-3-8',
          title: 'Teclas 3 y 8',
          description: 'Usa los dedos medios para presionar 3 y 8.',
          objective: 'Presionar 3 y 8 con los dedos medios.',
          content:
            'Usa tus dedos medios para presionar las teclas 3 y 8, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-50-es.mp3',
          targetKeys: ['3', '8'],
          order: 50,
        }),
        introduction({
          slug: 'fila-numerica-4-7',
          title: 'Teclas 4 y 7',
          description: 'Usa los dedos índices para presionar 4 y 7.',
          objective: 'Presionar 4 y 7 con los dedos índices.',
          content:
            'Usa tus dedos índices para presionar las teclas 4 y 7, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-51-es.mp3',
          targetKeys: ['4', '7'],
          order: 51,
        }),
        introduction({
          slug: 'fila-numerica-5-6',
          title: 'Teclas 5 y 6',
          description: 'Extiende tus dedos índices para llegar a 5 y 6.',
          objective: 'Presionar 5 y 6 sin perder la referencia en F y J.',
          content:
            'Usa tus dedos índices para presionar las teclas 5 y 6, luego regresa a la posición de descanso.',
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-52-es.mp3',
          targetKeys: ['5', '6'],
          order: 52,
        }),
        practice({
          slug: 'fila-numerica-practica-1',
          title: 'Fila numérica - Introducción',
          description: 'Practica las teclas numéricas.',
          objective: 'Familiarizarse con la posición de los números 1-0.',
          content: '12 23 34 45 56 67 78 89 90 09 98 87 76 65 54 43 32 21 10',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: [],
          allowed: `1234567890${SPACE}`,
          order: 53,
        }),
        practice({
          slug: 'fila-numerica-practica-2',
          title: 'Fila numérica - Pares básicos',
          description: 'Practica pares de teclas adyacentes.',
          objective: 'Coordinar movimientos entre dedos en la fila numérica.',
          content: '12 23 34 45 56 67 78 89 90 09 98 87 76 65 54 43 32 21',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: [],
          allowed: `1234567890${SPACE}`,
          order: 54,
        }),
        practice({
          slug: 'fila-numerica-practica-3',
          title: 'Mano izquierda - Fila numérica',
          description: 'Practica los números de la mano izquierda.',
          objective: 'Mover los dedos izquierdos en la fila numérica.',
          content: '1 2 3 4 5 5 4 3 2 1 12 23 34 45 54 43 32 21 1 2 3 4 5',
          focusKeys: ['1', '2', '3', '4', '5'],
          reviewKeys: [],
          allowed: `12345${SPACE}`,
          order: 55,
        }),
        practice({
          slug: 'fila-numerica-practica-4',
          title: 'Mano derecha - Fila numérica',
          description: 'Practica los números de la mano derecha.',
          objective: 'Mover los dedos derechos en la fila numérica.',
          content: '6 7 8 9 0 0 9 8 7 6 67 78 89 90 09 98 87 76 6 7 8 9 0',
          focusKeys: ['6', '7', '8', '9', '0'],
          reviewKeys: [],
          allowed: `67890${SPACE}`,
          order: 56,
        }),
        practice({
          slug: 'fila-numerica-practica-5',
          title: 'Patrones comunes',
          description: 'Coordina movimientos entre ambas manos.',
          objective: 'Escribir combinaciones numéricas letra a letra.',
          content: '12 34 56 78 90 09 87 65 43 21 13 24 35 46 57 68 79 80 91 02',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `1234567890asdfjklñ${SPACE}`,
          order: 57,
        }),
        practice({
          slug: 'fila-numerica-practica-6',
          title: 'Alternancia fila numérica',
          description: 'Alterna entre mano izquierda y derecha en fila numérica.',
          objective: 'Mejorar la coordinación entre ambas manos.',
          content: '1 6 2 7 3 8 4 9 5 0 0 5 9 4 8 3 7 2 6 1 1 6 2 7 3 8 4 9 5 0',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: [],
          allowed: `1234567890${SPACE}`,
          order: 58,
        }),
        practice({
          slug: 'fila-numerica-practica-7',
          title: 'Patrones comunes 2',
          description: 'Patrones alternados de fila numérica.',
          objective: 'Mejorar la fluidez entre manos.',
          content: '12 56 34 78 90 09 87 65 43 21 13 57 24 68 35 79 46 80 57 68 79',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `1234567890asdfjklñ${SPACE}`,
          order: 59,
        }),
        practice({
          slug: 'fila-numerica-practica-8',
          title: 'Patrones comunes 3',
          description: 'Combinaciones numéricas mixtas.',
          objective: 'Mejorar la precisión en números.',
          content:
            '12 34 56 78 90 21 43 65 87 09 13 24 35 46 57 68 79 80 91 02 14 25 36 47 58 69 70 81 92 03',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `1234567890asdfjklñ${SPACE}`,
          order: 60,
        }),
        practice({
          slug: 'fila-numerica-practica-9',
          title: 'Años con fila numérica',
          description: 'Practica escribiendo años.',
          objective: 'Escribir años y fechas con fluidez.',
          content: '1990 2000 2010 2020 2021 2022 2023 2024 1999 2001 2005 2015 2025',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `1234567890asdfjklñ${SPACE}`,
          order: 61,
        }),
        practice({
          slug: 'fila-numerica-practica-10',
          title: 'Combinaciones avanzadas',
          description: 'Secuencias mixtas para mayor velocidad.',
          objective: 'Aumentar la velocidad en fila numérica.',
          content: '1234567890 0987654321 13579 24680 1234 5678 9012 3456 7890 123456',
          focusKeys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
          reviewKeys: ['a', 's', 'd', 'f', 'j', 'k', 'l', 'ñ'],
          allowed: `1234567890asdfjklñ${SPACE}`,
          order: 62,
        }),

        introduction({
          slug: 'shift-introduccion',
          title: 'Mayúsculas con Shift',
          description: 'Usa Shift con el meñique de la mano contraria a la letra.',
          objective: 'Entender cómo combinar Shift con una letra.',
          content:
            'Ahora vamos a practicar el uso de la tecla Shift, Shift sirve para escribir letras mayúsculas, presiona Shift con el meñique de la mano contraria a la letra que quieres escribir, por ejemplo, para escribir Casa, presiona Shift con el meñique derecho y la letra C con la mano izquierda, luego suelta Shift y continúa escribiendo la palabra normalmente.',
          targetKeys: ['C'],
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-63-es.mp3',
          order: 63,
        }),
        practice({
          slug: 'shift-practica-mayusculas',
          title: 'Práctica de mayúsculas',
          description: 'Escribe dos palabras cortas con mayúscula inicial.',
          objective: 'Usar Shift una vez al inicio de cada palabra.',
          content: 'Casa Sol',
          focusKeys: ['C', 'S'],
          reviewKeys: ['Shift'],
          allowed: `CasaSol${SPACE}`,
          order: 64,
        }),
        practice({
          slug: 'shift-practica-refuerzo',
          title: 'Más mayúsculas con Shift',
          description: 'Practica más palabras con mayúscula inicial.',
          objective: 'Usar Shift con seguridad al inicio de una palabra.',
          content: 'Lago Flor Nube',
          focusKeys: ['L', 'F', 'N'],
          reviewKeys: ['Shift'],
          allowed: `LagoFlorNube${SPACE}`,
          order: 65,
        }),
        introduction({
          slug: 'acento-agudo-introduccion',
          title: 'La tecla de acento',
          description: 'Primero pulsa el acento y después la vocal.',
          objective: 'Escribir una vocal con acento.',
          content:
            'Para escribir una vocal con acento, primero presiona la tecla de acento, después presiona la vocal, por ejemplo, para escribir á, presiona acento y luego A.',
          targetKeys: ['á'],
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-66-es.mp3',
          order: 66,
        }),
        practice({
          slug: 'vocales-con-tilde',
          title: 'Vocales con tilde',
          description: 'Practica á, é, í, ó y ú.',
          objective: 'Escribir vocales y palabras simples con tilde.',
          content: 'á é í ó ú mamá papá café sofá lápiz árbol ratón camión corazón música',
          focusKeys: ['á', 'é', 'í', 'ó', 'ú'],
          reviewKeys: ['a', 'e', 'i', 'o', 'u'],
          allowed: allAlphabetic,
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-67-es.mp3',
          order: 67,
        }),
        introduction({
          slug: 'dieresis-introduccion',
          title: 'La diéresis',
          description: 'Usa la diéresis antes de la U.',
          objective: 'Escribir la letra ü.',
          content:
            'Para escribir ü, primero presiona la tecla de diéresis, después presiona la letra U.',
          targetKeys: ['ü'],
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-68-es.mp3',
          order: 68,
        }),
        practice({
          slug: 'palabras-con-dieresis',
          title: 'Palabras con diéresis',
          description: 'Practica palabras simples con ü.',
          objective: 'Escribir palabras que usan diéresis.',
          content: 'ü pingüino vergüenza bilingüe cigüeña',
          focusKeys: ['ü'],
          reviewKeys: ['u'],
          allowed: allAlphabetic,
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-69-es.mp3',
          order: 69,
        }),
        introduction({
          slug: 'teclas-de-uso-diario',
          title: 'Teclas para escribir mejor',
          description: 'Conoce Enter, Backspace y los signos de pregunta y exclamación.',
          objective: 'Reconocer teclas útiles para escribir frases completas.',
          content:
            'Enter baja a la siguiente línea, Backspace borra la última letra si te equivocas, usa los signos de pregunta y exclamación cuando una frase los necesita.',
          targetKeys: ['Enter', 'Backspace', '¿', '?', '¡', '!', ';', '.', ','],
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-76-es.mp3',
          order: 76,
        }),
        practice({
          slug: 'practica-final-integradora',
          title: 'Práctica final',
          description: 'Escribe frases reales con calma y precisión.',
          objective: 'Integrar letras, signos, números, mayúsculas, tildes y diéresis.',
          content:
            'Mi mamá tomó café en casa. ¿Dónde está el lápiz? ¡Qué buen día para practicar! El pingüino camina 10 pasos. Hoy escribí 3 frases con precisión.',
          focusKeys: ['á', 'é', 'í', 'ó', 'ú', 'ü', '¿', '?', '¡', '!', '.', ',', '1', '0', '3'],
          reviewKeys: ['Shift'],
          allowed: allDailyCharacters,
          audioUrl: '/audio/lessons/es/caracteres-alfabeticos/lesson-77-es.mp3',
          order: 77,
        }),
      ],
    },
  ],
};

for (const [index, lesson] of module.exports.modules[0].lessons.entries()) {
  lesson.order = index + 1;
  if (lesson.audioUrl) {
    lesson.audioUrl = `/audio/es/caracteres-alfabeticos/lesson-${lesson.order}-es.mp3`;
  }
}

const allLessons = module.exports.modules[0].lessons;
module.exports.modules = [
  {
    slug: 'fila-descanso',
    title: 'Módulo 1: Fila de descanso',
    description: 'Aprende la postura, los dedos y la fila donde descansan las manos.',
    order: 1,
    lessons: allLessons.slice(0, 21),
  },
  {
    slug: 'fila-superior',
    title: 'Módulo 2: Fila superior',
    description: 'Practica las teclas de la fila superior y regresa a la posición de descanso.',
    order: 2,
    lessons: allLessons.slice(21, 36),
  },
  {
    slug: 'fila-inferior',
    title: 'Módulo 3: Fila inferior',
    description: 'Practica las teclas de la fila inferior con calma y precisión.',
    order: 3,
    lessons: allLessons.slice(36, 51),
  },
  {
    slug: 'fila-numerica',
    title: 'Módulo 4: Fila numérica',
    description: 'Aprende a escribir números sin perder la posición de las manos.',
    order: 4,
    lessons: allLessons.slice(51, 66),
  },
  {
    slug: 'mayusculas-y-acentos',
    title: 'Módulo 5: Mayúsculas, tildes y diéresis',
    description: 'Usa Shift, acentos y diéresis para escribir correctamente.',
    order: 5,
    lessons: allLessons.slice(66, 73),
  },
  {
    slug: 'escritura-cotidiana',
    title: 'Módulo 6: Escritura cotidiana',
    description: 'Usa teclas comunes y completa una práctica final con frases reales.',
    order: 6,
    lessons: allLessons.slice(73),
  },
];
