ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTY_LATAM';
ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTY_UK';
ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTZ';
ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'COLEMAK';
