import type { Locale } from './locales';

export type AboutIdentityContent = {
  languagesTitle: string;
  summary: string;
  publicFeatures: string;
  courses: string;
  languages: string;
};

// Claims here map to public routes and the course catalogue served by KisoDesk.
export const ABOUT_IDENTITY_CONTENT: Readonly<Record<Locale, AboutIdentityContent>> = {
  cs: { languagesTitle: 'Jazyky', summary: 'KisoDesk je webová platforma pro procvičování psaní, rychlosti psaní, přesnosti a kurzy psaní a pravopisu.', publicFeatures: 'Veřejně dostupné jsou test psaní, katalog kurzů, seznamy lekcí a žebříček.', courses: 'KisoDesk poskytuje kurzy zobrazené v katalogu. Každý kurz uvádí svůj název, popis, jazyk, úroveň a lekce.', languages: 'Rozhraní KisoDesk podporuje 19 lokalizací.' },
  da: { languagesTitle: 'Sprog', summary: 'KisoDesk er en webplatform til øvelse i skrivning, skrivehastighed, nøjagtighed samt kurser i skrivning og stavning.', publicFeatures: 'Den offentlige del omfatter skriveprøven, kursuskataloget, lektionslisterne og ranglisten.', courses: 'KisoDesk leverer kurserne i kataloget. Hvert kursus viser navn, beskrivelse, sprog, niveau og lektioner.', languages: 'KisoDesk-grænsefladen understøtter 19 lokaliteter.' },
  de: { languagesTitle: 'Sprachen', summary: 'KisoDesk ist eine Webplattform für Tippübungen, Tippgeschwindigkeit, Genauigkeit sowie Kurse zu Tippen und Rechtschreibung.', publicFeatures: 'Öffentlich verfügbar sind der Tipp-Test, der Kurskatalog, die Lektionslisten und die Rangliste.', courses: 'KisoDesk stellt die im Katalog angezeigten Kurse bereit. Jeder Kurs zeigt Name, Beschreibung, Sprache, Niveau und Lektionen.', languages: 'Die KisoDesk-Oberfläche unterstützt 19 Gebietsschemata.' },
  'en-US': { languagesTitle: 'Languages', summary: 'KisoDesk is a web platform for typing practice, typing speed, accuracy, and typing and spelling courses.', publicFeatures: 'Public features include the typing test, course catalogue, lesson lists, and ranking.', courses: 'KisoDesk provides the courses shown in its catalogue. Each course states its name, description, language, level, and lessons.', languages: 'The KisoDesk interface supports 19 locales.' },
  'en-GB': { languagesTitle: 'Languages', summary: 'KisoDesk is a web platform for typing practice, typing speed, accuracy, and typing and spelling courses.', publicFeatures: 'Public features include the typing test, course catalogue, lesson lists, and ranking.', courses: 'KisoDesk provides the courses shown in its catalogue. Each course states its name, description, language, level, and lessons.', languages: 'The KisoDesk interface supports 19 locales.' },
  'es-ES': { languagesTitle: 'Idiomas', summary: 'KisoDesk es una plataforma web de práctica de mecanografía, velocidad de escritura, precisión y cursos de mecanografía y ortografía.', publicFeatures: 'Las funciones públicas incluyen la prueba de mecanografía, el catálogo de cursos, los listados de lecciones y el ranking.', courses: 'KisoDesk proporciona los cursos mostrados en su catálogo. Cada curso indica nombre, descripción, idioma, nivel y lecciones.', languages: 'La interfaz de KisoDesk admite 19 configuraciones regionales.' },
  'es-latam': { languagesTitle: 'Idiomas', summary: 'KisoDesk es una plataforma web de práctica de mecanografía, velocidad de escritura, precisión y cursos de mecanografía y ortografía.', publicFeatures: 'Las funciones públicas incluyen la prueba de mecanografía, el catálogo de cursos, los listados de lecciones y el ranking.', courses: 'KisoDesk proporciona los cursos mostrados en su catálogo. Cada curso indica nombre, descripción, idioma, nivel y lecciones.', languages: 'La interfaz de KisoDesk admite 19 configuraciones regionales.' },
  fr: { languagesTitle: 'Langues', summary: 'KisoDesk est une plateforme web de pratique de frappe, de vitesse de frappe, de précision et de cours de frappe et d’orthographe.', publicFeatures: 'Les fonctions publiques comprennent le test de frappe, le catalogue de cours, les listes de leçons et le classement.', courses: 'KisoDesk fournit les cours affichés dans son catalogue. Chaque cours indique son nom, sa description, sa langue, son niveau et ses leçons.', languages: 'L’interface KisoDesk prend en charge 19 paramètres régionaux.' },
  hr: { languagesTitle: 'Jezici', summary: 'KisoDesk je web-platforma za vježbanje tipkanja, brzinu pisanja, točnost te tečajeve tipkanja i pravopisa.', publicFeatures: 'Javne funkcije uključuju test tipkanja, katalog tečajeva, popise lekcija i ljestvicu poretka.', courses: 'KisoDesk pruža tečajeve prikazane u katalogu. Svaki tečaj navodi naziv, opis, jezik, razinu i lekcije.', languages: 'Sučelje KisoDeska podržava 19 lokalizacija.' },
  hu: { languagesTitle: 'Nyelvek', summary: 'A KisoDesk egy gépelési gyakorláshoz, gépelési sebességhez, pontossághoz, valamint gépelési és helyesírási kurzusokhoz készült webplatform.', publicFeatures: 'A nyilvános funkciók közé tartozik a gépelési teszt, a kurzuskatalógus, a leckelisták és a rangsor.', courses: 'A KisoDesk biztosítja a katalógusban megjelenő kurzusokat. Minden kurzus tartalmazza a nevét, leírását, nyelvét, szintjét és leckéit.', languages: 'A KisoDesk felülete 19 területi beállítást támogat.' },
  it: { languagesTitle: 'Lingue', summary: 'KisoDesk è una piattaforma web per esercitarsi nella digitazione, nella velocità di scrittura, nella precisione e con corsi di digitazione e ortografia.', publicFeatures: 'Le funzioni pubbliche includono il test di digitazione, il catalogo dei corsi, gli elenchi delle lezioni e la classifica.', courses: 'KisoDesk fornisce i corsi mostrati nel catalogo. Ogni corso indica nome, descrizione, lingua, livello e lezioni.', languages: 'L’interfaccia di KisoDesk supporta 19 impostazioni locali.' },
  nl: { languagesTitle: 'Talen', summary: 'KisoDesk is een webplatform voor typeoefeningen, typesnelheid, nauwkeurigheid en cursussen typen en spelling.', publicFeatures: 'Openbare functies zijn de typetest, de cursuscatalogus, lessenlijsten en de ranglijst.', courses: 'KisoDesk biedt de cursussen in de catalogus aan. Elke cursus vermeldt naam, beschrijving, taal, niveau en lessen.', languages: 'De KisoDesk-interface ondersteunt 19 landinstellingen.' },
  no: { languagesTitle: 'Språk', summary: 'KisoDesk er en nettplattform for skriveøving, skrivehastighet, nøyaktighet og kurs i skriving og rettskriving.', publicFeatures: 'Offentlige funksjoner inkluderer skrivetesten, kurskatalogen, leksjonslistene og rangeringen.', courses: 'KisoDesk tilbyr kursene som vises i katalogen. Hvert kurs oppgir navn, beskrivelse, språk, nivå og leksjoner.', languages: 'KisoDesk-grensesnittet støtter 19 lokaliteter.' },
  pl: { languagesTitle: 'Języki', summary: 'KisoDesk to platforma internetowa do ćwiczenia pisania, szybkości pisania, dokładności oraz kursów pisania i ortografii.', publicFeatures: 'Funkcje publiczne obejmują test pisania, katalog kursów, listy lekcji i ranking.', courses: 'KisoDesk udostępnia kursy widoczne w katalogu. Każdy kurs podaje nazwę, opis, język, poziom i lekcje.', languages: 'Interfejs KisoDesk obsługuje 19 ustawień regionalnych.' },
  'pt-BR': { languagesTitle: 'Idiomas', summary: 'KisoDesk é uma plataforma web de prática de digitação, velocidade de escrita, precisão e cursos de digitação e ortografia.', publicFeatures: 'Os recursos públicos incluem o teste de digitação, o catálogo de cursos, as listas de lições e o ranking.', courses: 'KisoDesk fornece os cursos exibidos no catálogo. Cada curso informa nome, descrição, idioma, nível e lições.', languages: 'A interface do KisoDesk oferece suporte a 19 localidades.' },
  'pt-PT': { languagesTitle: 'Idiomas', summary: 'KisoDesk é uma plataforma web de prática de escrita, velocidade de escrita, precisão e cursos de escrita e ortografia.', publicFeatures: 'As funções públicas incluem o teste de escrita, o catálogo de cursos, as listas de lições e a classificação.', courses: 'O KisoDesk disponibiliza os cursos apresentados no catálogo. Cada curso indica nome, descrição, idioma, nível e lições.', languages: 'A interface do KisoDesk suporta 19 definições regionais.' },
  ro: { languagesTitle: 'Limbi', summary: 'KisoDesk este o platformă web pentru exerciții de tastare, viteză de tastare, precizie și cursuri de tastare și ortografie.', publicFeatures: 'Funcțiile publice includ testul de tastare, catalogul de cursuri, listele de lecții și clasamentul.', courses: 'KisoDesk oferă cursurile afișate în catalog. Fiecare curs indică numele, descrierea, limba, nivelul și lecțiile.', languages: 'Interfața KisoDesk acceptă 19 setări regionale.' },
  sv: { languagesTitle: 'Språk', summary: 'KisoDesk är en webbplattform för skrivträning, skrivhastighet, noggrannhet samt kurser i skrivning och stavning.', publicFeatures: 'Offentliga funktioner omfattar skrivtestet, kurskatalogen, lektionslistor och rankning.', courses: 'KisoDesk tillhandahåller kurserna som visas i katalogen. Varje kurs anger namn, beskrivning, språk, nivå och lektioner.', languages: 'KisoDesk-gränssnittet har stöd för 19 språkinställningar.' },
  tr: { languagesTitle: 'Diller', summary: 'KisoDesk, yazma alıştırması, yazma hızı, doğruluk ve yazma ile imla kursları için bir web platformudur.', publicFeatures: 'Herkese açık özellikler yazma testi, kurs kataloğu, ders listeleri ve sıralamayı içerir.', courses: 'KisoDesk katalogda gösterilen kursları sunar. Her kurs adı, açıklaması, dili, seviyesi ve dersleriyle belirtilir.', languages: 'KisoDesk arayüzü 19 yerel ayarı destekler.' },
};
