// front-typing/lib/keyboardLayouts
import type { ContentLanguage, Locale } from './locales';
import { physicalFamilyHasKeyId, type PhysicalKeyId } from './keyboardPhysical';

export type KeyboardLayoutId =
  | 'qwerty-es'
  | 'qwerty-latam'
  | 'qwerty-en'
  | 'qwerty-us-intl'
  | 'qwerty-uk'
  | 'qwerty-ca-multilingual'
  | 'qwerty-br'
  | 'qwerty-pt'
  | 'qwerty-it'
  | 'azerty'
  | 'qwertz'
  | 'qwertz-cs'
  | 'qwerty-da'
  | 'qwertz-hr'
  | 'qwertz-hu'
  | 'qwerty-nl'
  | 'qwerty-no'
  | 'qwerty-pl'
  | 'qwerty-ro'
  | 'qwerty-sv'
  | 'qwerty-tr'
  | 'dvorak'
  | 'colemak';

export type KeyboardContentLanguage = ContentLanguage;
export type KeyboardPhysicalFamily = 'ANSI' | 'ISO' | 'ABNT2' | 'JIS' | 'KS' | 'BIG_ASS';

export type BackendLayoutCode =
  | 'QWERTY_ES'
  | 'QWERTY_LATAM'
  | 'QWERTY_US'
  | 'QWERTY_US_INTL'
  | 'QWERTY_UK'
  | 'QWERTY_CA_MULTILINGUAL'
  | 'QWERTY_BR'
  | 'QWERTY_PT'
  | 'QWERTY_IT'
  | 'AZERTY'
  | 'QWERTZ'
  | 'QWERTZ_CS'
  | 'QWERTY_DA'
  | 'QWERTZ_HR'
  | 'QWERTZ_HU'
  | 'QWERTY_NL'
  | 'QWERTY_NO'
  | 'QWERTY_PL'
  | 'QWERTY_RO'
  | 'QWERTY_SV'
  | 'QWERTY_TR'
  | 'DVORAK'
  | 'COLEMAK';

export interface DeadKeyDefinition {
  physicalKeyId: PhysicalKeyId;
  shiftKey: boolean;
  combiningMark: string;
  standaloneMark: string;
}

export interface KeyboardLayout {
  id: KeyboardLayoutId;
  name: string;
  description?: string;
  enabled: boolean;
  languageCodes: readonly Locale[];
  physicalType?: KeyboardPhysicalFamily;
  keys: Readonly<Record<PhysicalKeyId, string>>;
  shiftedKeys?: Readonly<Record<PhysicalKeyId, string>>;
  altGrKeys?: Readonly<Record<PhysicalKeyId, string>>;
  shiftAltGrKeys?: Readonly<Record<PhysicalKeyId, string>>;
  deadKeys?: readonly DeadKeyDefinition[];
}

export interface KeyboardLayoutCompatibility {
  layout: KeyboardLayout;
  compatible: boolean;
  missingPhysicalKeyIds: readonly PhysicalKeyId[];
  preferredForPhysicalFamily: boolean;
}

export const KEYBOARD_LAYOUT_STORAGE_KEY = 'typing-keyboard-layout';
export const KEYBOARD_PHYSICAL_FAMILY_STORAGE_KEY = 'typing-keyboard-physical-family';
export const DEFAULT_KEYBOARD_LAYOUT_ID: KeyboardLayoutId = 'qwerty-latam';

export const FRONTEND_TO_BACKEND_LAYOUT: Record<KeyboardLayoutId, BackendLayoutCode> = {
  'qwerty-es': 'QWERTY_ES',
  'qwerty-latam': 'QWERTY_LATAM',
  'qwerty-en': 'QWERTY_US',
  'qwerty-us-intl': 'QWERTY_US_INTL',
  'qwerty-uk': 'QWERTY_UK',
  'qwerty-ca-multilingual': 'QWERTY_CA_MULTILINGUAL',
  'qwerty-br': 'QWERTY_BR',
  'qwerty-pt': 'QWERTY_PT',
  'qwerty-it': 'QWERTY_IT',
  azerty: 'AZERTY',
  qwertz: 'QWERTZ',
  'qwertz-cs': 'QWERTZ_CS',
  'qwerty-da': 'QWERTY_DA',
  'qwertz-hr': 'QWERTZ_HR',
  'qwertz-hu': 'QWERTZ_HU',
  'qwerty-nl': 'QWERTY_NL',
  'qwerty-no': 'QWERTY_NO',
  'qwerty-pl': 'QWERTY_PL',
  'qwerty-ro': 'QWERTY_RO',
  'qwerty-sv': 'QWERTY_SV',
  'qwerty-tr': 'QWERTY_TR',
  dvorak: 'DVORAK',
  colemak: 'COLEMAK',
};

export const BACKEND_TO_FRONTEND_LAYOUT: Record<BackendLayoutCode, KeyboardLayoutId> = {
  QWERTY_ES: 'qwerty-es',
  QWERTY_LATAM: 'qwerty-latam',
  QWERTY_US: 'qwerty-en',
  QWERTY_US_INTL: 'qwerty-us-intl',
  QWERTY_UK: 'qwerty-uk',
  QWERTY_CA_MULTILINGUAL: 'qwerty-ca-multilingual',
  QWERTY_BR: 'qwerty-br',
  QWERTY_PT: 'qwerty-pt',
  QWERTY_IT: 'qwerty-it',
  AZERTY: 'azerty',
  QWERTZ: 'qwertz',
  QWERTZ_CS: 'qwertz-cs',
  QWERTY_DA: 'qwerty-da',
  QWERTZ_HR: 'qwertz-hr',
  QWERTZ_HU: 'qwertz-hu',
  QWERTY_NL: 'qwerty-nl',
  QWERTY_NO: 'qwerty-no',
  QWERTY_PL: 'qwerty-pl',
  QWERTY_RO: 'qwerty-ro',
  QWERTY_SV: 'qwerty-sv',
  QWERTY_TR: 'qwerty-tr',
  DVORAK: 'dvorak',
  COLEMAK: 'colemak',
};

const LETTER_KEYS = {
  P16: 'q',
  P17: 'w',
  P18: 'e',
  P19: 'r',
  P20: 't',
  P21: 'y',
  P22: 'u',
  P23: 'i',
  P24: 'o',
  P25: 'p',
  P30: 'a',
  P31: 's',
  P32: 'd',
  P33: 'f',
  P34: 'g',
  P35: 'h',
  P36: 'j',
  P37: 'k',
  P38: 'l',
  P44: 'z',
  P45: 'x',
  P46: 'c',
  P47: 'v',
  P48: 'b',
  P49: 'n',
  P50: 'm',
};
const DIGIT_KEYS = {
  P02: '1',
  P03: '2',
  P04: '3',
  P05: '4',
  P06: '5',
  P07: '6',
  P08: '7',
  P09: '8',
  P10: '9',
  P11: '0',
};
const COMMON_KEYS = { ...LETTER_KEYS, ...DIGIT_KEYS, P60: ' ', P41: '\n', P51: ',', P52: '.' };
const QWERTY_KEYS = { ...COMMON_KEYS };

const DEAD_KEY_MARKS = {
  acute: { combiningMark: '\u0301', standaloneMark: '´' },
  grave: { combiningMark: '\u0300', standaloneMark: '`' },
  diaeresis: { combiningMark: '\u0308', standaloneMark: '¨' },
  circumflex: { combiningMark: '\u0302', standaloneMark: '^' },
  tilde: { combiningMark: '\u0303', standaloneMark: '~' },
  caron: { combiningMark: '\u030C', standaloneMark: 'ˇ' },
  abovering: { combiningMark: '\u030A', standaloneMark: '˚' },
} as const;

type DeadKeyMark = keyof typeof DEAD_KEY_MARKS;

function makeDeadKey(
  physicalKeyId: string,
  shiftKey: boolean,
  mark: DeadKeyMark,
): DeadKeyDefinition {
  return { physicalKeyId: physicalKeyId as PhysicalKeyId, shiftKey, ...DEAD_KEY_MARKS[mark] };
}

export const KEYBOARD_LAYOUTS = [
  {
    id: 'qwerty-es',
    name: 'QWERTY Español',
    description: 'Distribución estándar para España',
    enabled: true,
    languageCodes: ['es-ES'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: 'º',
      P12: "'",
      P13: '¡',
      P26: '`',
      P27: '+',
      P39: 'ñ',
      P40: '´',
      P28: 'ç',
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: 'ª',
      P02: '!',
      P03: '"',
      P04: '·',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '¿',
      P26: '^',
      P27: '*',
      P39: 'Ñ',
      P40: '¨',
      P28: 'Ç',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    altGrKeys: { P03: '@', P04: '#', P05: '~', P06: '€' },
    deadKeys: [
      makeDeadKey('P26', false, 'grave'),
      makeDeadKey('P26', true, 'circumflex'),
      makeDeadKey('P40', false, 'acute'),
      makeDeadKey('P40', true, 'diaeresis'),
    ],
  },
  {
    id: 'qwerty-latam',
    name: 'QWERTY Latinoamericano',
    description: 'Distribución para Latinoamérica',
    enabled: true,
    languageCodes: ['es-latam'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '|',
      P12: "'",
      P13: '¿',
      P26: '´',
      P27: '+',
      P39: 'ñ',
      P40: '{',
      P28: '}',
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: '°',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '¡',
      P26: '¨',
      P27: '*',
      P39: 'Ñ',
      P40: '[',
      P28: ']',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    deadKeys: [makeDeadKey('P26', false, 'acute'), makeDeadKey('P26', true, 'diaeresis')],
  },
  {
    id: 'qwerty-en',
    name: 'QWERTY US',
    description: 'Distribución estadounidense',
    enabled: true,
    languageCodes: ['en-US'],
    physicalType: 'ANSI',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: '-',
      P13: '=',
      P26: '[',
      P27: ']',
      P39: ';',
      P40: "'",
      P28: '\\',
      P53: '/',
    },
    shiftedKeys: {
      P01: '~',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: '{',
      P27: '}',
      P39: ':',
      P40: '"',
      P28: '|',
      P51: '<',
      P52: '>',
      P53: '?',
    },
  },
  {
    id: 'qwerty-us-intl',
    name: 'US International',
    description: 'Distribución estadounidense con teclas muertas para acentos',
    enabled: false,
    languageCodes: [],
    physicalType: 'ANSI',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: '-',
      P13: '=',
      P26: '[',
      P27: ']',
      P39: ';',
      P40: '´',
      P28: '\\',
      P53: '/',
    },
    shiftedKeys: {
      P01: '~',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: '{',
      P27: '}',
      P39: ':',
      P40: '¨',
      P28: '|',
      P51: '<',
      P52: '>',
      P53: '?',
    },
    deadKeys: [
      makeDeadKey('P07', true, 'circumflex'),
      makeDeadKey('P40', false, 'acute'),
      makeDeadKey('P40', true, 'diaeresis'),
      makeDeadKey('P01', false, 'grave'),
      makeDeadKey('P01', true, 'tilde'),
    ],
  },
  {
    id: 'qwerty-uk',
    name: 'QWERTY Reino Unido',
    description: 'Distribución británica',
    enabled: true,
    languageCodes: ['en-GB'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: '-',
      P13: '=',
      P26: '[',
      P27: ']',
      P39: ';',
      P40: "'",
      P28: '#',
      P43: '\\',
      P53: '/',
    },
    shiftedKeys: {
      P01: '¬',
      P02: '!',
      P03: '"',
      P04: '£',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: '{',
      P27: '}',
      P39: ':',
      P40: '@',
      P28: '~',
      P43: '|',
      P51: '<',
      P52: '>',
      P53: '?',
    },
  },
  {
    id: 'qwerty-ca-multilingual',
    name: 'Canadian Multilingual',
    description: 'Distribución canadiense multilingüe',
    enabled: false,
    languageCodes: [],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '/',
      P12: '-',
      P13: '=',
      P26: '^',
      P27: 'ç',
      P39: ';',
      P40: 'è',
      P28: 'à',
      P43: 'ù',
      P53: 'é',
    },
    shiftedKeys: {
      P01: '\\',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '?',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: '¨',
      P27: 'Ç',
      P39: ':',
      P40: 'È',
      P28: 'À',
      P43: 'Ù',
      P51: "'",
      P52: '"',
      P53: 'É',
    },
    deadKeys: [makeDeadKey('P26', false, 'circumflex'), makeDeadKey('P26', true, 'diaeresis')],
  },
  {
    id: 'qwerty-br',
    name: 'QWERTY Português (Brasil)',
    description: 'Distribuição brasileira ABNT2',
    enabled: true,
    languageCodes: ['pt-BR'],
    physicalType: 'ABNT2',
    keys: {
      ...QWERTY_KEYS,
      P01: "'",
      P12: '-',
      P13: '=',
      P26: '´',
      P27: '[',
      P39: 'ç',
      P40: '~',
      P28: ']',
      P43: '\\',
      P53: ';',
      P54: '/',
    },
    shiftedKeys: {
      P01: '"',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '¨',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: '`',
      P27: '{',
      P39: 'Ç',
      P40: '^',
      P28: '}',
      P43: '|',
      P51: '<',
      P52: '>',
      P53: ':',
      P54: '?',
    },
    deadKeys: [
      makeDeadKey('P07', true, 'diaeresis'),
      makeDeadKey('P26', false, 'acute'),
      makeDeadKey('P26', true, 'grave'),
      makeDeadKey('P40', false, 'tilde'),
      makeDeadKey('P40', true, 'circumflex'),
    ],
  },
  {
    id: 'qwerty-pt',
    name: 'QWERTY Português',
    description: 'Distribuição padrão utilizada em Portugal',
    enabled: true,
    languageCodes: ['pt-PT'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '\\',
      P12: "'",
      P13: '«',
      P26: '+',
      P27: '´',
      P39: 'ç',
      P40: 'º',
      P28: '~',
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: '|',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '»',
      P26: '*',
      P27: '`',
      P39: 'Ç',
      P40: 'ª',
      P28: '^',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    deadKeys: [
      makeDeadKey('P27', false, 'acute'),
      makeDeadKey('P27', true, 'grave'),
      makeDeadKey('P28', false, 'tilde'),
      makeDeadKey('P28', true, 'circumflex'),
    ],
  },
  {
    id: 'qwerty-it',
    name: 'QWERTY Italiano',
    description: 'Distribuzione standard utilizzata in Italia',
    enabled: true,
    languageCodes: ['it'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '\\',
      P12: "'",
      P13: 'ì',
      P26: 'è',
      P27: '+',
      P39: 'ò',
      P40: 'à',
      P28: 'ù',
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: '|',
      P02: '!',
      P03: '"',
      P04: '£',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '^',
      P26: 'é',
      P27: '*',
      P39: 'ç',
      P40: '°',
      P28: '§',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
  },
  {
    id: 'azerty',
    name: 'AZERTY Francés',
    description: 'Distribución francesa',
    enabled: true,
    languageCodes: ['fr'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '²',
      P02: '&',
      P03: 'é',
      P04: '"',
      P05: "'",
      P06: '(',
      P07: '-',
      P08: 'è',
      P09: '_',
      P10: 'ç',
      P11: 'à',
      P12: ')',
      P13: '=',
      P16: 'a',
      P17: 'z',
      P26: '^',
      P27: '$',
      P30: 'q',
      P39: 'm',
      P40: 'ù',
      P28: '*',
      P43: '<',
      P44: 'w',
      P50: ',',
      P51: ';',
      P52: ':',
      P53: '!',
    },
    shiftedKeys: {
      P01: '~',
      P02: '1',
      P03: '2',
      P04: '3',
      P05: '4',
      P06: '5',
      P07: '6',
      P08: '7',
      P09: '8',
      P10: '9',
      P11: '0',
      P12: '°',
      P13: '+',
      P26: '¨',
      P27: '£',
      P39: 'M',
      P40: '%',
      P28: 'µ',
      P43: '>',
      P50: '?',
      P51: '.',
      P52: '/',
      P53: '§',
    },
    deadKeys: [makeDeadKey('P26', false, 'circumflex'), makeDeadKey('P26', true, 'diaeresis')],
  },
  {
    id: 'qwertz',
    name: 'QWERTZ Alemán',
    description: 'Distribución alemana',
    enabled: true,
    languageCodes: ['de'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '^',
      P12: 'ß',
      P13: '´',
      P21: 'z',
      P26: 'ü',
      P27: '+',
      P39: 'ö',
      P40: 'ä',
      P28: '#',
      P43: '<',
      P44: 'y',
      P53: '-',
    },
    shiftedKeys: {
      P01: '°',
      P02: '!',
      P03: '"',
      P04: '§',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '`',
      P26: 'Ü',
      P27: '*',
      P39: 'Ö',
      P40: 'Ä',
      P28: "'",
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    deadKeys: [
      makeDeadKey('P13', false, 'acute'),
      makeDeadKey('P13', true, 'grave'),
      makeDeadKey('P01', false, 'circumflex'),
    ],
  },
  {
    id: 'qwertz-cs',
    name: 'QWERTZ Český',
    description: 'Distribución estándar checa',
    enabled: true,
    languageCodes: ['cs'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: ';',
      P02: '+',
      P03: 'ě',
      P04: 'š',
      P05: 'č',
      P06: 'ř',
      P07: 'ž',
      P08: 'ý',
      P09: 'á',
      P10: 'í',
      P11: 'é',
      P12: '=',
      P13: '´',
      P21: 'z',
      P26: 'ú',
      P27: ')',
      P39: 'ů',
      P40: '§',
      P28: '¨',
      P43: '\\',
      P44: 'y',
      P53: '-',
    },
    shiftedKeys: {
      P01: '˚',
      P02: '1',
      P03: '2',
      P04: '3',
      P05: '4',
      P06: '5',
      P07: '6',
      P08: '7',
      P09: '8',
      P10: '9',
      P11: '0',
      P12: '%',
      P13: 'ˇ',
      P26: '/',
      P27: '(',
      P39: '"',
      P40: '!',
      P28: "'",
      P43: '|',
      P51: '?',
      P52: ':',
      P53: '_',
    },
    deadKeys: [
      makeDeadKey('P13', false, 'acute'),
      makeDeadKey('P13', true, 'caron'),
      makeDeadKey('P01', true, 'abovering'),
      makeDeadKey('P28', false, 'diaeresis'),
    ],
  },
  {
    id: 'qwerty-da',
    name: 'QWERTY Dansk',
    description: 'Distribución estándar danesa',
    enabled: true,
    languageCodes: ['da'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '½',
      P12: '+',
      P13: '´',
      P26: 'å',
      P27: '¨',
      P39: 'æ',
      P40: 'ø',
      P28: "'",
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: '§',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '¤',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '`',
      P26: 'Å',
      P27: '^',
      P39: 'Æ',
      P40: 'Ø',
      P28: '*',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    deadKeys: [
      makeDeadKey('P13', false, 'acute'),
      makeDeadKey('P13', true, 'grave'),
      makeDeadKey('P27', false, 'diaeresis'),
      makeDeadKey('P27', true, 'circumflex'),
    ],
  },
  {
    id: 'qwertz-hr',
    name: 'QWERTZ Hrvatski',
    description: 'Distribución estándar croata',
    enabled: true,
    languageCodes: ['hr'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: "'",
      P13: '+',
      P21: 'z',
      P26: 'š',
      P27: 'đ',
      P39: 'č',
      P40: 'ć',
      P28: 'ž',
      P43: '<',
      P44: 'y',
      P53: '-',
    },
    shiftedKeys: {
      P01: '~',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '*',
      P26: 'Š',
      P27: 'Đ',
      P39: 'Č',
      P40: 'Ć',
      P28: 'Ž',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
  },
  {
    id: 'qwertz-hu',
    name: 'QWERTZ Magyar',
    description: 'Distribución estándar húngara',
    enabled: true,
    languageCodes: ['hu'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '0',
      P11: 'ö',
      P12: 'ü',
      P13: 'ó',
      P21: 'z',
      P26: 'ő',
      P27: 'ú',
      P39: 'é',
      P40: 'á',
      P28: 'ű',
      P43: 'í',
      P44: 'y',
      P53: '-',
    },
    shiftedKeys: {
      P01: '§',
      P02: "'",
      P03: '"',
      P04: '+',
      P05: '!',
      P06: '%',
      P07: '/',
      P08: '=',
      P09: '(',
      P10: ')',
      P11: 'Ö',
      P12: 'Ü',
      P13: 'Ó',
      P26: 'Ő',
      P27: 'Ú',
      P39: 'É',
      P40: 'Á',
      P28: 'Ű',
      P43: 'Í',
      P51: '?',
      P52: ':',
      P53: '_',
    },
  },
  {
    id: 'qwerty-nl',
    name: 'QWERTY Nederlands',
    description: 'Distribución estándar neerlandesa',
    enabled: true,
    languageCodes: ['nl'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '@',
      P12: '/',
      P13: '°',
      P26: '¨',
      P27: '*',
      P39: '+',
      P40: '´',
      P28: '<',
      P43: ']',
      P53: '-',
    },
    shiftedKeys: {
      P01: '§',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '&',
      P08: '_',
      P09: '(',
      P10: ')',
      P11: "'",
      P12: '?',
      P13: '~',
      P26: '^',
      P27: '|',
      P39: '±',
      P40: '`',
      P28: '>',
      P43: '[',
      P51: ';',
      P52: ':',
      P53: '=',
    },
    deadKeys: [
      makeDeadKey('P13', true, 'tilde'),
      makeDeadKey('P26', false, 'diaeresis'),
      makeDeadKey('P26', true, 'circumflex'),
      makeDeadKey('P40', false, 'acute'),
      makeDeadKey('P40', true, 'grave'),
    ],
  },
  {
    id: 'qwerty-no',
    name: 'QWERTY Norsk',
    description: 'Distribución estándar noruega',
    enabled: true,
    languageCodes: ['no'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '|',
      P12: '+',
      P13: '\\',
      P26: 'å',
      P27: '¨',
      P39: 'ø',
      P40: 'æ',
      P28: "'",
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: '§',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '¤',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '`',
      P26: 'Å',
      P27: '^',
      P39: 'Ø',
      P40: 'Æ',
      P28: '*',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    deadKeys: [
      makeDeadKey('P13', true, 'grave'),
      makeDeadKey('P27', false, 'diaeresis'),
      makeDeadKey('P27', true, 'circumflex'),
    ],
  },
  {
    id: 'qwerty-pl',
    name: 'QWERTY Polski',
    description: 'Distribución estándar polaca',
    enabled: true,
    languageCodes: ['pl'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: '-',
      P13: '=',
      P26: '[',
      P27: ']',
      P39: ';',
      P40: "'",
      P28: '\\',
      P43: '<',
      P53: '/',
    },
    shiftedKeys: {
      P01: '~',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: '{',
      P27: '}',
      P39: ':',
      P40: '"',
      P28: '|',
      P43: '>',
      P51: '<',
      P52: '>',
      P53: '?',
    },
  },
  {
    id: 'qwerty-ro',
    name: 'QWERTY Română',
    description: 'Distribución estándar rumana',
    enabled: true,
    languageCodes: ['ro'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '„',
      P12: '-',
      P13: '=',
      P26: 'ă',
      P27: 'î',
      P39: 'ș',
      P40: 'ț',
      P28: 'â',
      P43: '\\',
      P53: '/',
    },
    shiftedKeys: {
      P01: '”',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P26: 'Ă',
      P27: 'Î',
      P39: 'Ș',
      P40: 'Ț',
      P28: 'Â',
      P43: '|',
      P51: ';',
      P52: ':',
      P53: '?',
    },
  },
  {
    id: 'qwerty-sv',
    name: 'QWERTY Svenska',
    description: 'Distribución estándar sueca',
    enabled: true,
    languageCodes: ['sv'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '§',
      P12: '+',
      P13: '´',
      P26: 'å',
      P27: '¨',
      P39: 'ö',
      P40: 'ä',
      P28: "'",
      P43: '<',
      P53: '-',
    },
    shiftedKeys: {
      P01: '½',
      P02: '!',
      P03: '"',
      P04: '#',
      P05: '¤',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '`',
      P26: 'Å',
      P27: '^',
      P39: 'Ö',
      P40: 'Ä',
      P28: '*',
      P43: '>',
      P51: ';',
      P52: ':',
      P53: '_',
    },
    deadKeys: [
      makeDeadKey('P13', false, 'acute'),
      makeDeadKey('P13', true, 'grave'),
      makeDeadKey('P27', false, 'diaeresis'),
      makeDeadKey('P27', true, 'circumflex'),
    ],
  },
  {
    id: 'qwerty-tr',
    name: 'QWERTY Türkçe',
    description: 'Distribución estándar turca',
    enabled: true,
    languageCodes: ['tr'],
    physicalType: 'ISO',
    keys: {
      ...QWERTY_KEYS,
      P01: '"',
      P12: '*',
      P13: '-',
      P23: 'ı',
      P26: 'ğ',
      P27: 'ü',
      P39: 'ş',
      P40: 'i',
      P28: ',',
      P43: '<',
      P51: 'ö',
      P52: 'ç',
      P53: '.',
    },
    shiftedKeys: {
      P01: 'é',
      P02: '!',
      P03: "'",
      P04: '^',
      P05: '+',
      P06: '%',
      P07: '&',
      P08: '/',
      P09: '(',
      P10: ')',
      P11: '=',
      P12: '?',
      P13: '_',
      P23: 'I',
      P26: 'Ğ',
      P27: 'Ü',
      P39: 'Ş',
      P40: 'İ',
      P28: ';',
      P43: '>',
      P51: 'Ö',
      P52: 'Ç',
      P53: ':',
    },
  },
  {
    id: 'dvorak',
    name: 'Dvorak',
    description: 'Distribución ergonómica Dvorak',
    enabled: false,
    languageCodes: [],
    physicalType: 'ANSI',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: '[',
      P13: ']',
      P16: "'",
      P17: ',',
      P18: '.',
      P19: 'p',
      P20: 'y',
      P21: 'f',
      P22: 'g',
      P23: 'c',
      P24: 'r',
      P25: 'l',
      P26: '/',
      P27: '=',
      P31: 'o',
      P32: 'e',
      P33: 'u',
      P34: 'i',
      P35: 'd',
      P36: 'h',
      P37: 't',
      P38: 'n',
      P39: 's',
      P40: '-',
      P28: '\\',
      P44: ';',
      P45: 'q',
      P46: 'j',
      P47: 'k',
      P48: 'x',
      P49: 'b',
      P51: 'w',
      P52: 'v',
      P53: 'z',
    },
    shiftedKeys: {
      P01: '~',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '{',
      P13: '}',
      P16: '"',
      P17: '<',
      P18: '>',
      P26: '?',
      P27: '+',
      P39: 'S',
      P40: '_',
      P28: '|',
      P44: ':',
      P51: 'W',
      P52: 'V',
      P53: 'Z',
    },
  },
  {
    id: 'colemak',
    name: 'Colemak',
    description: 'Distribución ergonómica Colemak',
    enabled: false,
    languageCodes: [],
    physicalType: 'ANSI',
    keys: {
      ...QWERTY_KEYS,
      P01: '`',
      P12: '-',
      P13: '=',
      P18: 'f',
      P19: 'p',
      P20: 'g',
      P21: 'j',
      P22: 'l',
      P23: 'u',
      P24: 'y',
      P25: ';',
      P26: '[',
      P27: ']',
      P31: 'r',
      P32: 's',
      P33: 't',
      P34: 'd',
      P36: 'n',
      P37: 'e',
      P38: 'i',
      P39: 'o',
      P40: "'",
      P28: '\\',
      P49: 'k',
      P53: '/',
    },
    shiftedKeys: {
      P01: '~',
      P02: '!',
      P03: '@',
      P04: '#',
      P05: '$',
      P06: '%',
      P07: '^',
      P08: '&',
      P09: '*',
      P10: '(',
      P11: ')',
      P12: '_',
      P13: '+',
      P25: ':',
      P26: '{',
      P27: '}',
      P39: 'O',
      P40: '"',
      P28: '|',
      P51: '<',
      P52: '>',
      P53: '?',
    },
  },
] as unknown as KeyboardLayout[];

export function getKeyOutput(
  layout: KeyboardLayout,
  physicalKeyId: PhysicalKeyId,
  shiftKey = false,
  altGrKey = false,
): string | undefined {
  if (altGrKey) {
    const altGrOutput = shiftKey
      ? layout.shiftAltGrKeys?.[physicalKeyId]
      : layout.altGrKeys?.[physicalKeyId];
    if (altGrOutput !== undefined) return altGrOutput;
  }
  const baseOutput = layout.keys[physicalKeyId];
  if (!shiftKey) return baseOutput;

  const explicitShiftOutput = layout.shiftedKeys?.[physicalKeyId];
  if (explicitShiftOutput !== undefined) return explicitShiftOutput;

  if (baseOutput && /^\p{L}$/u.test(baseOutput)) {
    if (layout.id === 'qwerty-tr') {
      if (baseOutput === 'i') return 'İ';
      if (baseOutput === 'ı') return 'I';
    }
    return baseOutput.toUpperCase();
  }

  return baseOutput;
}

export function getDeadKey(
  layout: KeyboardLayout,
  physicalKeyId: PhysicalKeyId,
  shiftKey: boolean,
): DeadKeyDefinition | undefined {
  return layout.deadKeys?.find(
    (deadKey) => deadKey.physicalKeyId === physicalKeyId && deadKey.shiftKey === shiftKey,
  );
}

export const getEnabledLayouts = (): KeyboardLayout[] =>
  KEYBOARD_LAYOUTS.filter((layout) => layout.enabled);

export function layoutSupportsLocale(
  layout: KeyboardLayout,
  locale: KeyboardContentLanguage | Locale | string | null | undefined,
): boolean {
  if (!locale) return false;
  const normalizedLocale = locale.toLowerCase();

  return layout.languageCodes.some((languageCode) => {
    const normalizedLanguageCode = languageCode.toLowerCase();
    return (
      normalizedLanguageCode === normalizedLocale ||
      (!normalizedLocale.includes('-') && normalizedLanguageCode.startsWith(`${normalizedLocale}-`))
    );
  });
}

function getLayoutPhysicalKeyIds(layout: KeyboardLayout): PhysicalKeyId[] {
  return Array.from(
    new Set<PhysicalKeyId>([
      ...(Object.keys(layout.keys) as PhysicalKeyId[]),
      ...(Object.keys(layout.shiftedKeys ?? {}) as PhysicalKeyId[]),
      ...(Object.keys(layout.altGrKeys ?? {}) as PhysicalKeyId[]),
      ...(Object.keys(layout.shiftAltGrKeys ?? {}) as PhysicalKeyId[]),
      ...(layout.deadKeys?.map((deadKey) => deadKey.physicalKeyId) ?? []),
    ]),
  );
}

export function getKeyboardLayoutCompatibility(
  layout: KeyboardLayout,
  physicalFamily: KeyboardPhysicalFamily,
): KeyboardLayoutCompatibility {
  const missingPhysicalKeyIds = getLayoutPhysicalKeyIds(layout).filter(
    (physicalKeyId) => !physicalFamilyHasKeyId(physicalFamily, physicalKeyId),
  );

  return {
    layout,
    compatible: missingPhysicalKeyIds.length === 0,
    missingPhysicalKeyIds,
    preferredForPhysicalFamily: layout.physicalType === physicalFamily,
  };
}

export function getEnabledLayoutsForLocale(
  locale: KeyboardContentLanguage | Locale | string | null | undefined,
  physicalFamily: KeyboardPhysicalFamily,
): KeyboardLayoutCompatibility[] {
  return getEnabledLayouts()
    .filter((layout) => layoutSupportsLocale(layout, locale))
    .map((layout) => getKeyboardLayoutCompatibility(layout, physicalFamily))
    .sort(
      (left, right) =>
        Number(right.compatible) - Number(left.compatible) ||
        Number(right.preferredForPhysicalFamily) - Number(left.preferredForPhysicalFamily) ||
        left.layout.name.localeCompare(right.layout.name),
    );
}
export const getDefaultLayout = (): KeyboardLayout =>
  KEYBOARD_LAYOUTS.find((layout) => layout.id === DEFAULT_KEYBOARD_LAYOUT_ID) ??
  KEYBOARD_LAYOUTS[0];
export function getDefaultLayoutForLanguage(language?: string | null): KeyboardLayout {
  const layoutByLanguage: Partial<Record<ContentLanguage, KeyboardLayoutId>> = {
    cs: 'qwertz-cs',
    da: 'qwerty-da',
    de: 'qwertz',
    en: 'qwerty-en',
    es: 'qwerty-latam',
    fr: 'azerty',
    hr: 'qwertz-hr',
    hu: 'qwertz-hu',
    it: 'qwerty-it',
    nl: 'qwerty-nl',
    no: 'qwerty-no',
    pl: 'qwerty-pl',
    pt: 'qwerty-pt',
    ro: 'qwerty-ro',
    sv: 'qwerty-sv',
    tr: 'qwerty-tr',
  };
  return getEnabledLayoutById(
    layoutByLanguage[language as ContentLanguage] ?? DEFAULT_KEYBOARD_LAYOUT_ID,
  );
}

export function getDefaultLayoutForLocale(locale?: string | null): KeyboardLayout {
  const canonicalLocale = locale?.trim() ?? '';
  const matchedLayout = getEnabledLayouts().find((layout) =>
    layout.languageCodes.some((languageCode) =>
      canonicalLocale.toLowerCase().startsWith(languageCode.toLowerCase()),
    ),
  );
  if (matchedLayout) return matchedLayout;
  return getDefaultLayoutForLanguage(canonicalLocale.split('-')[0].toLowerCase());
}
export const getLayoutById = (id: string | null | undefined): KeyboardLayout | undefined =>
  KEYBOARD_LAYOUTS.find((layout) => layout.id === id);
export const getEnabledLayoutById = (id: string | null | undefined): KeyboardLayout =>
  getEnabledLayouts().find((layout) => layout.id === id) ?? getDefaultLayout();
export function resolveKeyboardLayout({
  layoutId,
  language,
}: {
  layoutId?: string | null;
  language?: string | null;
}): KeyboardLayout {
  return (
    getEnabledLayouts().find((layout) => layout.id === layoutId) ??
    getDefaultLayoutForLanguage(language)
  );
}
export const normalizeLayoutId = (id: string | null | undefined): KeyboardLayoutId =>
  getEnabledLayoutById(id).id;
export const toBackendLayoutCode = (layout: KeyboardLayoutId | KeyboardLayout): BackendLayoutCode =>
  FRONTEND_TO_BACKEND_LAYOUT[typeof layout === 'string' ? layout : layout.id];
export const fromBackendLayoutCode = (
  layoutCode: BackendLayoutCode | null | undefined,
): KeyboardLayoutId | null =>
  layoutCode ? (BACKEND_TO_FRONTEND_LAYOUT[layoutCode] ?? null) : null;
