import type { Locale } from './locales';

export type PracticeSeoContent = {
  title: string;
  intro: string;
  metrics: string;
  instructions: string;
  results: string;
  tips: string;
};

// Visible, server-rendered explanatory copy for the public practice page.
// Keep claims limited to the speed, accuracy and result features the product shows.
export const PRACTICE_SEO_CONTENT: Readonly<Record<Locale, PracticeSeoContent>> = {
  cs: { title: 'Test rychlosti psaní', intro: 'Vyzkoušejte si psaní na klávesnici s krátkým textem a zjistěte, jak rychle a přesně píšete.', metrics: 'WPM udává počet slov za minutu a přesnost ukazuje podíl správně napsaných znaků.', instructions: 'Zvolte režim, klikněte do textu a začněte psát. Po dokončení můžete načíst nový text.', results: 'Porovnávejte rychlost i přesnost. Vyšší rychlost má smysl jen tehdy, když zůstává čitelný správný zápis.', tips: 'Začněte plynulým tempem, dívejte se na text místo na klávesnici a opakujte cvičení, ve kterých děláte chyby.' },
  da: { title: 'Test af skrivehastighed', intro: 'Prøv din skrivehastighed med en kort tekst og se, hvor hurtigt og præcist du skriver.', metrics: 'WPM viser ord pr. minut, og nøjagtighed viser, hvor stor en del af tegnene der er skrevet korrekt.', instructions: 'Vælg en tilstand, klik i teksten, og begynd at skrive. Hent en ny tekst, når du er færdig.', results: 'Sammenlign både hastighed og nøjagtighed. En højere hastighed er mest nyttig, når teksten stadig er korrekt.', tips: 'Skriv roligt, se på teksten frem for tastaturet, og gentag de øvelser, hvor du laver flest fejl.' },
  de: { title: 'Tippgeschwindigkeitstest', intro: 'Teste dein Tippen mit einem kurzen Text und sieh, wie schnell und genau du auf der Tastatur schreibst.', metrics: 'WPM steht für Wörter pro Minute. Die Genauigkeit zeigt, welcher Anteil deiner Zeichen korrekt ist.', instructions: 'Wähle einen Modus, klicke in den Text und beginne zu tippen. Nach dem Ergebnis kannst du einen neuen Text laden.', results: 'Betrachte Geschwindigkeit und Genauigkeit zusammen. Mehr Tempo hilft nur, wenn der Text weiterhin korrekt bleibt.', tips: 'Tippe gleichmäßig, schaue auf den Text statt auf die Tastatur und wiederhole Übungen mit häufigen Fehlern.' },
  'en-US': { title: 'Typing speed test', intro: 'Test your keyboard skills with a short text and see how quickly and accurately you type.', metrics: 'WPM means words per minute. Accuracy shows the share of characters you typed correctly.', instructions: 'Choose a mode, click the text, and start typing. Load a new text when you finish.', results: 'Read speed and accuracy together. Faster typing is useful only when your text remains correct.', tips: 'Start at a steady pace, look at the text instead of the keyboard, and repeat exercises where errors appear often.' },
  'en-GB': { title: 'Typing speed test', intro: 'Test your keyboard skills with a short text and see how quickly and accurately you type.', metrics: 'WPM means words per minute. Accuracy shows the proportion of characters you typed correctly.', instructions: 'Choose a mode, click the text, and start typing. Load a new text when you finish.', results: 'Read speed and accuracy together. Faster typing is useful only when your text remains correct.', tips: 'Start at a steady pace, look at the text rather than the keyboard, and repeat exercises where errors appear often.' },
  'es-ES': { title: 'Prueba de velocidad de escritura', intro: 'Pon a prueba tu escritura con un texto breve y descubre qué velocidad y precisión tienes al teclear.', metrics: 'WPM, también llamado PPM o palabras por minuto, indica tu velocidad; la precisión muestra qué proporción de caracteres escribiste correctamente.', instructions: 'Elige un modo, haz clic en el texto y empieza a escribir. Al terminar puedes cargar otro texto.', results: 'Interpreta velocidad y precisión juntas. Escribir más rápido solo ayuda si el texto sigue siendo correcto.', tips: 'Empieza a un ritmo constante, mira el texto en lugar del teclado y repite los ejercicios donde más fallas.' },
  'es-latam': { title: 'Prueba de velocidad de escritura', intro: 'Pon a prueba tu escritura con un texto corto y descubre qué velocidad y precisión tienes al teclear.', metrics: 'WPM, también llamado PPM o palabras por minuto, indica tu velocidad; la precisión muestra qué proporción de caracteres escribiste correctamente.', instructions: 'Elige un modo, haz clic en el texto y empieza a escribir. Al terminar puedes cargar otro texto.', results: 'Interpreta velocidad y precisión juntas. Escribir más rápido solo ayuda si el texto sigue siendo correcto.', tips: 'Empieza a un ritmo constante, mira el texto en lugar del teclado y repite los ejercicios donde cometes más errores.' },
  fr: { title: 'Test de vitesse de frappe', intro: 'Testez votre frappe avec un court texte et découvrez votre vitesse et votre précision au clavier.', metrics: 'Le WPM indique les mots par minute et la précision indique la part de caractères saisis correctement.', instructions: 'Choisissez un mode, cliquez dans le texte et commencez à saisir. Chargez un nouveau texte à la fin.', results: 'Lisez vitesse et précision ensemble. Taper plus vite est utile seulement si le texte reste correct.', tips: 'Commencez à un rythme régulier, regardez le texte plutôt que le clavier et répétez les exercices où les erreurs reviennent.' },
  hr: { title: 'Test brzine tipkanja', intro: 'Isprobajte tipkanje na kratkom tekstu i saznajte koliko brzo i točno pišete.', metrics: 'WPM označava riječi u minuti, a točnost pokazuje udio ispravno unesenih znakova.', instructions: 'Odaberite način rada, kliknite u tekst i počnite tipkati. Nakon završetka možete učitati novi tekst.', results: 'Promatrajte brzinu i točnost zajedno. Veća brzina vrijedi samo ako tekst ostane ispravan.', tips: 'Počnite ravnomjernim tempom, gledajte tekst umjesto tipkovnice i ponavljajte vježbe u kojima često griješite.' },
  hu: { title: 'Gépelési sebességteszt', intro: 'Próbálja ki gépelését egy rövid szöveggel, és nézze meg, milyen gyorsan és pontosan ír.', metrics: 'A WPM a percenkénti szavakat jelenti, a pontosság pedig a helyesen leütött karakterek arányát mutatja.', instructions: 'Válasszon módot, kattintson a szövegbe, és kezdjen gépelni. Befejezés után új szöveget tölthet be.', results: 'A sebességet és a pontosságot együtt értelmezze. A nagyobb sebesség csak helyes szöveggel hasznos.', tips: 'Kezdjen egyenletes tempóban, a szöveget nézze, ne a billentyűzetet, és ismételje a gyakori hibás gyakorlatokat.' },
  it: { title: 'Test di velocità di digitazione', intro: 'Prova la tua digitazione con un testo breve e scopri quanto scrivi velocemente e con precisione.', metrics: 'WPM indica le parole al minuto e la precisione mostra la quota di caratteri digitati correttamente.', instructions: 'Scegli una modalità, fai clic nel testo e inizia a digitare. Al termine puoi caricare un nuovo testo.', results: 'Valuta velocità e precisione insieme. Digitare più velocemente è utile solo se il testo resta corretto.', tips: 'Inizia con un ritmo costante, guarda il testo invece della tastiera e ripeti gli esercizi con più errori.' },
  nl: { title: 'Typesnelheidtest', intro: 'Test je typevaardigheid met een korte tekst en ontdek hoe snel en nauwkeurig je typt.', metrics: 'WPM betekent woorden per minuut. Nauwkeurigheid toont welk deel van de tekens je correct hebt getypt.', instructions: 'Kies een modus, klik in de tekst en begin te typen. Laad een nieuwe tekst wanneer je klaar bent.', results: 'Bekijk snelheid en nauwkeurigheid samen. Sneller typen helpt alleen als de tekst correct blijft.', tips: 'Begin in een gelijkmatig tempo, kijk naar de tekst in plaats van het toetsenbord en herhaal oefeningen met veel fouten.' },
  no: { title: 'Skrivehastighetstest', intro: 'Test skrivingen din med en kort tekst og se hvor raskt og nøyaktig du skriver.', metrics: 'WPM betyr ord per minutt, og nøyaktighet viser hvor stor andel av tegnene du skrev riktig.', instructions: 'Velg en modus, klikk i teksten og begynn å skrive. Last inn en ny tekst når du er ferdig.', results: 'Se hastighet og nøyaktighet sammen. Høyere hastighet hjelper bare når teksten fortsatt er riktig.', tips: 'Start i et jevnt tempo, se på teksten i stedet for tastaturet og gjenta øvelser der feilene ofte kommer.' },
  pl: { title: 'Test szybkości pisania', intro: 'Sprawdź pisanie na krótkim tekście i zobacz, jak szybko oraz dokładnie piszesz na klawiaturze.', metrics: 'WPM oznacza słowa na minutę, a dokładność pokazuje udział poprawnie wpisanych znaków.', instructions: 'Wybierz tryb, kliknij w tekst i zacznij pisać. Po zakończeniu możesz wczytać nowy tekst.', results: 'Oceniaj szybkość i dokładność razem. Szybsze pisanie ma sens tylko wtedy, gdy tekst pozostaje poprawny.', tips: 'Zacznij w równym tempie, patrz na tekst zamiast na klawiaturę i powtarzaj ćwiczenia z częstymi błędami.' },
  'pt-BR': { title: 'Teste de velocidade de digitação', intro: 'Teste sua digitação com um texto curto e descubra com que velocidade e precisão você escreve.', metrics: 'WPM indica palavras por minuto e a precisão mostra a proporção de caracteres digitados corretamente.', instructions: 'Escolha um modo, clique no texto e comece a digitar. Ao terminar, você pode carregar outro texto.', results: 'Analise velocidade e precisão juntas. Digitar mais rápido só ajuda quando o texto continua correto.', tips: 'Comece em um ritmo constante, olhe para o texto em vez do teclado e repita exercícios com erros frequentes.' },
  'pt-PT': { title: 'Teste de velocidade de escrita', intro: 'Teste a sua escrita com um texto curto e descubra a velocidade e precisão com que escreve.', metrics: 'WPM indica palavras por minuto e a precisão mostra a proporção de caracteres escritos corretamente.', instructions: 'Escolha um modo, clique no texto e comece a escrever. No fim, pode carregar outro texto.', results: 'Analise velocidade e precisão em conjunto. Escrever mais depressa só ajuda se o texto continuar correcto.', tips: 'Comece a um ritmo regular, olhe para o texto em vez do teclado e repita exercícios com erros frequentes.' },
  ro: { title: 'Test de viteză de tastare', intro: 'Testează-ți tastarea cu un text scurt și află cât de repede și corect scrii.', metrics: 'WPM înseamnă cuvinte pe minut, iar precizia arată proporția caracterelor tastate corect.', instructions: 'Alege un mod, apasă în text și începe să tastezi. La final poți încărca un text nou.', results: 'Privește viteza și precizia împreună. Viteza mai mare ajută doar când textul rămâne corect.', tips: 'Începe într-un ritm constant, uită-te la text în loc de tastatură și repetă exercițiile cu erori frecvente.' },
  sv: { title: 'Skrivhastighetstest', intro: 'Testa din skrivning med en kort text och se hur snabbt och noggrant du skriver.', metrics: 'WPM betyder ord per minut och noggrannhet visar hur stor andel av tecknen du skrev korrekt.', instructions: 'Välj ett läge, klicka i texten och börja skriva. Ladda en ny text när du är klar.', results: 'Se hastighet och noggrannhet tillsammans. Högre hastighet hjälper bara när texten fortfarande är korrekt.', tips: 'Börja i ett jämnt tempo, titta på texten i stället för tangentbordet och upprepa övningar med återkommande fel.' },
  tr: { title: 'Yazma hızı testi', intro: 'Kısa bir metinle yazma becerinizi test edin ve ne kadar hızlı ve doğru yazdığınızı görün.', metrics: 'WPM dakikadaki kelime sayısını gösterir. Doğruluk, karakterlerin ne kadarını doğru yazdığınızı gösterir.', instructions: 'Bir mod seçin, metne tıklayın ve yazmaya başlayın. Bitirdiğinizde yeni bir metin yükleyebilirsiniz.', results: 'Hızı ve doğruluğu birlikte değerlendirin. Daha hızlı yazmak yalnızca metin doğru kaldığında faydalıdır.', tips: 'Dengeli bir tempoyla başlayın, klavye yerine metne bakın ve sık hata yaptığınız alıştırmaları tekrarlayın.' },
};
