module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [2, 'always', ['feat', 'fix', 'docs', 'style', 'refactor', 'test', 'chore', 'ci']],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],

    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'usuarios',
        'perfiles',
        'lecciones',
        'sesiones',
        'recomendador',
        'progreso',
        'profesores',
        'reportes',
        'ranking',
        'i18n',
        'accesibilidad',
        'contenido',
        'notificaciones',
        'anticheat',
        'admin',
        'realtime',
        'api',
        'db',
        'prisma',
        'scripts',
        'tests',
        'ci',
        'docs',
        'chore',
        'deps',
      ],
    ],
    'scope-empty': [2, 'never'],

    'subject-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],

    'header-max-length': [2, 'always', 100],
    'body-leading-blank': [1, 'always'],
    'footer-leading-blank': [1, 'always'],
  },
};
