ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTY_US_INTL';
ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTY_CA_MULTILINGUAL';
ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTY_PT';
ALTER TYPE "LayoutCode" ADD VALUE IF NOT EXISTS 'QWERTY_IT';
